[project]
name = "itmo-ai-timetable-ics"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Roman Solomatin", email = "36135455+Samoed@users.noreply.github.com"},
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}
dependencies = [
    "ics>=0.7.2",
    "pytz>=2024.1",
    "openpyxl>=3.1.5",
]

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
lint = [
    "ruff>=0.6.2",
    "pre-commit>=3.8.0",
]
typing = [
    "mypy>=1.11.1",
    "types-openpyxl>=3.1.5.20240822",
    "types-pytz>=2024.1.0.20240417",
]

[tool.ruff]
fix = true
target-version = "py310"
line-length = 120
extend-include = ["*.ipynb"]

[tool.ruff.lint]
select= [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
    "RUF", # ruff
    "N",   # flake8-naming
#    "ANN", # flake8-annotations
    "S",   # flake8-bandit
    "BLE", # flake8-blind-except
    "A",   # flake8-builtins
#    "COM", # flake8-trailing-comma
    "C4",  # flake8-comprehensions
    "DTZ", # flake8-datetimez
#    "EM",  # flake8-errmsg
    "ISC", # flake8-implicit-str-concat
    "LOG", # flake8-logging
#    "G",   # flake8-logging-format
    "PIE", # flake8-pie
    "INP", # flake8-no-pep420
    "T20", # flake8-print
    "PT",  # flake8-pytest-style
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "ARG", # flake8-unused-arguments
    "PTH", # flake8-use-pathlib
    "PL",  # pylint
    "NPY", # NumPy-specific rules
#    "FAST", # fastapi
#    "TCH", # flake8-type-checking
#    "TID", # flake8-tidy-imports
#    "D",   # pydocstyle
]
ignore = [
    "RUF001",
    "ISC001",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F405", "F403", "D"]

[tool.mypy]
python_version = "3.10"
strict = true
warn_redundant_casts = true
# plugins = ["numpy.typing.mypy_plugin"]

[[tool.mypy.overrides]]
module = [
    "scipy",
    "sklearn",
]
ignore_missing_imports = true
