"""remove_id_from_user_course

Revision ID: c35b1b08a8b9
Revises: e68d1c12a16b
Create Date: 2024-09-08 00:17:10.376136

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c35b1b08a8b9"
down_revision: str | None = "e68d1c12a16b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_course", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_course", sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
