"""init

Revision ID: 83bf6072b0b1
Revises:
Create Date: 2024-08-25 22:21:49.476864

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83bf6072b0b1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("meeting_link", sa.String(), nullable=True),
        sa.Column("notion_link", sa.String(), nullable=True),
        sa.Column("tg_chat_link", sa.String(), nullable=True),
        sa.Column("timetable_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("user_real_name", sa.String(), nullable=True),
        sa.Column("user_tg_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "class",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column(
            "class_status",
            sa.Enum("need_to_delete", "deleted", "need_to_update", "synced", name="classstatus"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_course",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "course_id", "id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_course")
    op.drop_table("class")
    op.drop_table("user")
    op.drop_table("course")
    # ### end Alembic commands ###
    # https://github.com/sqlalchemy/alembic/issues/89
    sa.Enum(name="classstatus").drop(op.get_bind(), checkfirst=False)  # type: ignore[no-untyped-call]
