"""add_class_type

Revision ID: e8c0bfa43dc2
Revises: c9bcd9f756e9
Create Date: 2024-08-31 23:09:13.500556

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8c0bfa43dc2"
down_revision: str | None = "c9bcd9f756e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("class", sa.Column("class_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("class", "class_type")
    # ### end Alembic commands ###
