"""add_gcal_event_id

Revision ID: c9bcd9f756e9
Revises: d049d1e83016
Create Date: 2024-08-31 22:14:02.753700

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9bcd9f756e9"
down_revision: str | None = "d049d1e83016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("class", sa.Column("gcal_event_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("class", "gcal_event_id")
    # ### end Alembic commands ###
